In [5]:
import numpy as np
from scipy import io

# Step 1: Create a 4x4 array of ones
array_ones = np.ones((4, 4))

# Step 2: Save the array to a text file
np.savetxt('test.text', array_ones)

# Step 3: Load the array back from the text file
loaded_array = np.loadtxt('test.text')

# Step 4: Print the loaded array
print("Loaded array from test.text:")
print(loaded_array)


Loaded array from test.text:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
from scipy.special import cbrt

# Define the input values
values = [27, 64, 891]

# Compute cube roots
cube_roots = cbrt(values)

# Print the results
print("Cube roots:", cube_roots)


Cube roots: [3.         4.         9.62260299]


In [7]:
import numpy as np
from scipy import linalg

# Step 1: Create the 2x2 matrix
matrix = np.array([[4, 5],
                   [3, 2]])

# Step 2: Calculate the determinant
det_value = linalg.det(matrix)

# Step 3: Print the result
print("Determinant of the matrix is:", det_value)


Determinant of the matrix is: -7.0


In [8]:
import numpy as np
from scipy import linalg

# Define the matrix
matrix = np.array([[4, 5],
                   [3, 2]])

# Calculate the inverse
inverse_matrix = linalg.inv(matrix)

# Print the result
print("Inverse of the matrix:")
print(inverse_matrix)


Inverse of the matrix:
[[-0.28571429  0.71428571]
 [ 0.42857143 -0.57142857]]


In [9]:
import numpy as np
from scipy import linalg

# Define the 2x2 matrix
matrix = np.array([[5, 4],
                   [6, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = linalg.eig(matrix)

# Display results
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 9.+0.j -1.+0.j]

Eigenvectors:
[[ 0.70710678 -0.5547002 ]
 [ 0.70710678  0.83205029]]


In [11]:
import numpy as np
from scipy.sparse import csr_matrix

# Define dense data
data_A = np.array([[0, 0, 1], [2, 0, 0], [0, 3, 0]])
data_B = np.array([[0, 4, 0], [0, 0, 5], [6, 0, 0]])

# Convert to sparse format (Compressed Sparse Row)
A = csr_matrix(data_A)
B = csr_matrix(data_B)

print("Sparse Matrix A:\n", A)
print("\nSparse Matrix B:\n", B)
print("\nDense A:\n", A.toarray())
C = A + B
print("\nA + B:\n", C.toarray())
D = A.dot(B)
print("\nA dot B:\n", D.toarray())
print("\nTranspose of A:\n", A.transpose().toarray())
print("\nNumber of non-zero elements in A:", A.nnz)



Sparse Matrix A:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	1
  (1, 0)	2
  (2, 1)	3

Sparse Matrix B:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 1)	4
  (1, 2)	5
  (2, 0)	6

Dense A:
 [[0 0 1]
 [2 0 0]
 [0 3 0]]

A + B:
 [[0 4 1]
 [2 0 5]
 [6 3 0]]

A dot B:
 [[ 6  0  0]
 [ 0  8  0]
 [ 0  0 15]]

Transpose of A:
 [[0 2 0]
 [0 0 3]
 [1 0 0]]

Number of non-zero elements in A: 3
